id = "xuancong-vynora"
name = "Vynora"
version = "0.0.1"
schema_version = 1
authors = ["Xuancong Meng <xuancongmeng@gmail.com>"]
description = "a theme for Zed based on the Monokai Pro color scheme"
repository = "https://github.com/QuarkPixel/Vynora"
